(() => {
  const cards=[...document.querySelectorAll('.place-card')],groups={category:document.querySelector('.london-type-filters'),region:document.querySelector('.london-region-filters'),area:document.querySelector('.london-area-filters')},count=document.querySelector('.cg-intro p'),empty=document.querySelector('.empty-state'),state={category:'all',region:'all',area:'all'};
  const activate=(group,active)=>group.querySelectorAll('button').forEach(button=>{const on=button===active;button.classList.toggle('active',on);button.setAttribute('aria-pressed',String(on))});
  const updateAreas=()=>groups.area.querySelectorAll('[data-area]').forEach(button=>{button.hidden=button.dataset.regionGroup!=='all'&&state.region!=='all'&&button.dataset.regionGroup!==state.region});
  const apply=()=>{let shown=0;cards.forEach(card=>{const visible=(state.category==='all'||card.dataset.category===state.category)&&(state.region==='all'||card.dataset.region===state.region)&&(state.area==='all'||card.dataset.area===state.area);card.classList.toggle('hidden',!visible);if(visible)shown++});empty.hidden=shown>0;count.textContent=`${shown} ${shown===1?'recommendation':'recommendations'}`};
  ['category','region','area'].forEach(key=>groups[key].querySelectorAll(`[data-${key}]`).forEach(button=>button.addEventListener('click',()=>{state[key]=button.dataset[key];activate(groups[key],button);if(key==='region'){state.area='all';activate(groups.area,groups.area.querySelector('[data-area="all"]'));updateAreas()}apply()})));
  const map=document.querySelector('[data-view-panel="map"]'),views=[...document.querySelectorAll('[data-guide-view]')];
  const mapSelect=document.querySelector('#london-map-place');
  cards.forEach(card=>{const option=document.createElement('option');option.value=card.querySelector('.place-actions a.primary').href;option.textContent=card.querySelector('h3').textContent;mapSelect.appendChild(option)});
  const updateMap=()=>{const query=new URL(mapSelect.value).searchParams.get('query');map.querySelector('iframe').src=`https://www.google.com/maps?q=${encodeURIComponent(query)}&output=embed`;map.querySelector('.london-map-directions').href=mapSelect.value};
  mapSelect.addEventListener('change',updateMap);
  const setView=view=>{const isMap=view==='map';document.body.classList.toggle('map-view-active',isMap);map.hidden=!isMap;if(isMap&&!map.querySelector('iframe').hasAttribute('src'))updateMap();views.forEach(button=>{const active=button.dataset.guideView===view;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});if(isMap||location.hash==='#map')history.replaceState(null,'',isMap?'#map':'#list')};
  views.forEach(button=>button.addEventListener('click',()=>{setView(button.dataset.guideView);if(button.dataset.guideView==='map')document.querySelector('.guide-view-switcher').scrollIntoView({block:'start'})}));document.querySelector('[data-footer-map]').addEventListener('click',event=>{event.preventDefault();setView('map');scrollTo({top:document.querySelector('.guide-view-switcher').offsetTop,behavior:'smooth'})});updateAreas();apply();setView(location.hash==='#map'?'map':'list');
})();
