const VENUES={
  'simple-coffee':{name:'Simple Coffee',city:'Paris',category:'Café',address:'78 Rue des Martyrs, Paris',instagram:'https://www.instagram.com/simple.coffeeparis/',directions:'https://www.google.com/maps/search/?api=1&query=Simple%20Coffee%2078%20Rue%20des%20Martyrs%20Paris%20France',image:'assets/city_paris.jpg',guide:'paris-guide.html'},
  'merlo-cafe':{name:'Merlo Café',city:'Paris',category:'Café',address:'Le Marais, Paris',instagram:'https://www.instagram.com/merlocafe_/',directions:'https://www.google.com/maps/search/?api=1&query=Merlo%20Cafe%20Le%20Marais%20Paris%20France',image:'assets/city_paris.jpg',guide:'paris-guide.html'},
  'grave-cafe':{name:'Grave Café',city:'Paris',category:'Café',address:'Le Marais, Paris',instagram:'https://www.instagram.com/grave.cafe/',directions:'https://www.google.com/maps/search/?api=1&query=Grave%20Cafe%20Le%20Marais%20Paris%20France',image:'assets/city_paris.jpg',guide:'paris-guide.html'},
  'klear-labs':{name:'Klear Labs',city:'London',category:'Bakery · Specialty Coffee',address:'Golborne Road, London',instagram:'https://www.instagram.com/klear.labs/',directions:'https://www.google.com/maps/search/?api=1&query=Klear%20Labs%20Golborne%20Road%20London%20United%20Kingdom',image:'assets/city_london.jpg',guide:'london-guide.html'},
  'soi-and-co':{name:'Soi & Co',city:'Berlin',category:'Café',address:'Mitte, Berlin',instagram:'https://www.instagram.com/soiandco/',directions:'https://www.google.com/maps/search/?api=1&query=Soi%20%26%20Co%20Mitte%20Berlin%20Germany',image:'assets/city_berlin.jpg',guide:'berlin-guide.html'},
  'riviera':{name:'Riviera',city:'Copenhagen',category:'Café',address:'Nansensgade, Copenhagen',instagram:'https://www.instagram.com/riviera_cph/',directions:'https://www.google.com/maps/search/?api=1&query=Riviera%20Nansensgade%20Copenhagen%20Denmark',image:'assets/city_copenhagen.jpg',guide:'copenhagen-guide.html'},
  'lokal':{name:'Lokal',city:'Copenhagen',category:'Café',address:'Vesterbro, Copenhagen',instagram:'https://www.instagram.com/lokalcph/',directions:'https://www.google.com/maps/search/?api=1&query=Lokal%20Vesterbro%20Copenhagen%20Denmark',image:'assets/city_copenhagen.jpg',guide:'copenhagen-guide.html'}
};
const params=new URLSearchParams(location.search);const key=params.get('place')||'klear-labs';const venue=VENUES[key]||VENUES['klear-labs'];
document.title=`${venue.name} · The Dog Friendly Guide`;
document.documentElement.style.setProperty('--venue-image',`url('${venue.image}')`);
document.querySelector('[data-name]').textContent=venue.name;document.querySelector('[data-city]').textContent=`${venue.city} · ${venue.category}`;document.querySelector('[data-address]').textContent=venue.address;document.querySelector('[data-instagram]').href=venue.instagram;document.querySelector('[data-directions]').href=venue.directions;document.querySelector('[data-back]').href=venue.guide;
const fav=document.querySelector('[data-favourite]');const storeKey='dfg:favourites';const saved=()=>JSON.parse(localStorage.getItem(storeKey)||'[]');function paint(){const on=saved().includes(key);fav.classList.toggle('saved',on);fav.textContent=on?'♥ Saved to Favourites':'♡ Add to Favourites';}fav.addEventListener('click',()=>{const current=saved();const next=current.includes(key)?current.filter(x=>x!==key):[...current,key];localStorage.setItem(storeKey,JSON.stringify(next));paint();});paint();